/* variable "resource_group_location" {
  default     = "swedencentral"
  description = "Location of the resource group."
} */

variable "location" {
  type        = string
  description = "(Required) Azure region where resources will be created"
  default     = "swedencentral"
}

variable "resource_group_name" {
  default     = ""
  type        = string
  description = "The resource group name. If not provided, the resource group will be generated by the label module in the format namespace-stage-name"
}

variable "default_tags" {
  description = "Default billing tags to be applied across all resources"
  type        = map(string)
  default     = {}
}

variable "linux_machine_name" {
  default     = "virtual-ubuntu-desktop-vm"
  type        = string
  description = "The virtual machine name"
}

variable "vm_size" {
  default     = "Standard_D2as_v5"
  type        = string
  description = "The size of the VM"
}

variable "client_ip" {
  type        = string
  description = "IP adress to the client accessing the virtual machine"
}

# ---------------------------------------------------------------------------------------------------------------------
# Source image reference variables
# ---------------------------------------------------------------------------------------------------------------------

variable "source_imgage_reference_publisher" {
  default     = "canonical"
  type        = string
  description = "The publisher of the image"
}

variable "source_imgage_reference_offer" {
  default     = "0001-com-ubuntu-minimal-jammy"
  type        = string
  description = "The image offer"
}

variable "source_imgage_reference_sku" {
  default     = "minimal-22_04-lts-gen2"
  type        = string
  description = "The image SKU"
}

variable "source_imgage_reference_version" {
  default     = "latest"
  type        = string
  description = "The version of the image"
}

# ---------------------------------------------------------------------------------------------------------------------
# label_ - resource group label variables - used in terraform-null-label
# ---------------------------------------------------------------------------------------------------------------------

variable "label_namespace" {
  description = "Namespace, which could be your organization name. First item in naming sequence."
  default     = ""
  type        = string
}

variable "label_stage" {
  description = "Stage, e.g. `prod`, `staging`, `dev`, or `test`. Second item in naming sequence."
  default     = ""
  type        = string
}

variable "label_name" {
  description = "Name, which could be the name of your solution or app. Third item in naming sequence."
  default     = ""
  type        = string
}