variable "resource_group_location" {
  default     = "swedencentral"
  description = "Location of the resource group."
}

variable "location" {
  type        = string
  description = "(Required) Azure region where resources will be created"
  default     = "swedencentral"
}

variable "resource_group_name" {
  default     = ""
  type        = string
  description = "The resource group name. If not provided, the resource group will be generated by the label module in the format namespace-stage-name"
}

variable "default_tags" {
  description = "Default billing tags to be applied across all resources"
  type        = map(string)
  default     = {}
}

variable "linux_machine_name" {
  default     = "virtual-ubuntu-desktop-vm"
  type        = string
  description = "The virtual machine name"
}

variable "vm_size" {
  default     = "Standard_D2as_v5"
  type        = string
  description = "The size of the VM"
}

variable "storage_account_tier" {
  type        = string
  default     = "Standard"
  description = "Defines the Tier to use for this storage account. Valid options are Standard and Premium"
}
variable "storage_account_replication_type" {
  type        = string
  default     = "LRS"
  description = "Defines the type of replication to use for this storage account. Valid options are LRS, GRS, RAGRS, ZRS, GZRS and RAGZRS."
}

variable "nsg_source_port" {
  default     = "Standard_D2as_v5"
  type        = string
  description = "The size of the VM"
}

variable "client_ip" {
  type        = string
  description = "IP adress to the client accessing the virtual machine"
}

# ---------------------------------------------------------------------------------------------------------------------
# Source image reference variables
# ---------------------------------------------------------------------------------------------------------------------

variable "source_imgage_reference_publisher" {
  default     = "canonical"
  type        = string
  description = "The publisher of the image"
}

variable "source_imgage_reference_offer" {
  default     = "0001-com-ubuntu-minimal-jammy"
  type        = string
  description = "The image offer"
}

variable "source_imgage_reference_sku" {
  default     = "minimal-22_04-lts-gen2"
  type        = string
  description = "The image SKU"
}

variable "source_imgage_reference_version" {
  default     = "latest"
  type        = string
  description = "The version of the image"
}

variable "source_plan_name" {
  default     = "pay-per-use"
  type        = string
  description = "The source plan of the image"
}

variable "source_plan_publisher" {
  default     = "noricumcloudsolutions1600524477681"
  type        = string
  description = "The source plan publisher"
}

variable "source_plan_product" {
  default     = "ubuntu-22-gui"
  type        = string
  description = "The source plan product"
}

# ---------------------------------------------------------------------------------------------------------------------
# label_ - resource group label variables - used in terraform-null-label
# ---------------------------------------------------------------------------------------------------------------------

variable "label_namespace" {
  description = "Namespace, which could be your organization name. First item in naming sequence."
  default     = ""
  type        = string
}

variable "label_stage" {
  description = "Stage, e.g. `prod`, `staging`, `dev`, or `test`. Second item in naming sequence."
  default     = ""
  type        = string
}

variable "label_name" {
  description = "Name, which could be the name of your solution or app. Third item in naming sequence."
  default     = ""
  type        = string
}

variable "label_attributes" {
  type        = list(string)
  default     = []
  description = "Additional attributes, e.g. `1`"
}

# ---------------------------------------------------------------------------------------------------------------------
# kv- - KeyVault permissions
# ---------------------------------------------------------------------------------------------------------------------

variable "kv-key-permissions-full" {
  type        = list(string)
  description = "List of full key permissions, must be one or more from the following: Backup, Create, Decrypt, Delete, Encrypt, Get, Import, List, Purge, Recover, Restore, Sign, UnwrapKey, Update, Verify, WrapKey, Release, Rotate, GetRotationPolicy, and SetRotationPolicy."
  default     = ["Backup", "Create", "Decrypt", "Delete", "Encrypt", "Get", "Import", "List", "Purge", "Recover", "Restore", "Sign", "UnwrapKey", "Update", "Verify", "WrapKey", "Release", "Rotate", "GetRotationPolicy", "SetRotationPolicy"]
}

variable "kv-secret-permissions-full" {
  type        = list(string)
  description = "List of full secret permissions, must be one or more from the following: Backup, Delete, Get, List, Purge, Recover, Restore and Set."
  default     = ["Backup", "Delete", "Get", "List", "Purge", "Recover", "Restore", "Set"]
}

variable "kv-certificate-permissions-full" {
  type        = list(string)
  description = "List of full certificate permissions, must be one or more from the following: Backup, Create, Delete, DeleteIssuers, Get, GetIssuers, Import, List, ListIssuers, ManageContacts, ManageIssuers, Purge, Recover, Restore, SetIssuers and Update"
  default     = ["Backup", "Create", "Delete", "DeleteIssuers", "Get", "GetIssuers", "Import", "List", "ListIssuers", "ManageContacts", "ManageIssuers", "Purge", "Recover", "Restore", "SetIssuers", "Update"]
}

variable "kv-storage-permissions-full" {
  type        = list(string)
  description = "List of full storage permissions, must be one or more from the following: Backup, Delete, DeleteSAS, Get, GetSAS, List, ListSAS, Purge, Recover, RegenerateKey, Restore, Set, SetSAS and Update."
  default     = ["Backup", "Delete", "DeleteSAS", "Get", "GetSAS", "List", "ListSAS", "Purge", "Recover", "RegenerateKey", "Restore", "Set", "SetSAS", "Update"]
}